WebProtectoraMilpatitas/Models/TestAnimalIdealViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebProtectoraMilpatitas.Models
{
    public class TestAnimalIdealViewModel
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Display(Prompt ="Afición favorita", Description ="Afición favorita", Name = "¿Cuál es tu afición favorita?")]
        [Required(ErrorMessage ="Debe indicar una afición favorita")]
        [StringLength(maximumLength:100, ErrorMessage ="La afición no puede tener más de 100 caracteres")]
        public string AficionFavorita { get; set; }

        [Display(Prompt = "Personalidad", Description = "Personalidad", Name = "¿Qué te describe mejor?")]
        [Required(ErrorMessage = "Debe indicar una personalidad")]
        [StringLength(maximumLength: 100, ErrorMessage = "La personalidad no puede tener más de 100 caracteres")]
        public string Personalidad { get; set; }

        [Display(Prompt = "Color Favorito", Description = "Color Favorito", Name = "¿Cúal es tu color favorito?")]
        [Required(ErrorMessage = "Debe indicar un color favorito")]
        [StringLength(maximumLength: 100, ErrorMessage = "El color no puede tener más de 50 caracteres")]
        public string ColorFavorito { get; set; }

        public string idUsuario { get; set; }

        public string Resultado { get; set; }
    }
}

WebProtectoraMilpatitas/Controllers/TestAnimalIdealController.cs
using ProtectoraMilpatitasGenNHibernate.CAD.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebProtectoraMilpatitas.Assemblers;
using WebProtectoraMilpatitas.Models;
using System.Web.UI.WebControls;

namespace WebProtectoraMilpatitas.Controllers
{
    [Authorize]
    public class TestAnimalIdealController : BasicController
    {
        // GET: TestAnimalIdeal
        public ActionResult Index(int? page, string sortOrder, string aficionSearch, string colorSearch, string personSearch, string usuSearch)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            TestAnimalIdealCAD testCAD = new TestAnimalIdealCAD(session);
            TestAnimalIdealCEN testCEN = new TestAnimalIdealCEN(testCAD);

            IList<TestAnimalIdealEN> listEN = testCEN.Dame_Todos(0, -1);

            ViewBag.AficionSort = String.IsNullOrEmpty(sortOrder) ? "aficion_desc" : "";
            ViewBag.PersonalidadSort = String.IsNullOrEmpty(sortOrder) ? "personalidad_desc" : "";
            ViewBag.ColorSort = String.IsNullOrEmpty(sortOrder) ? "color_desc" : "";
            ViewBag.UsuarioSort = String.IsNullOrEmpty(sortOrder) ? "usuario_desc" : "";

            if (!String.IsNullOrEmpty(aficionSearch))
            {
                listEN = listEN.Where(s => s.AficionFavorita.Contains(aficionSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(colorSearch))
            {
                listEN = listEN.Where(s => s.ColorFavorito.Contains(colorSearch)).ToList();
            }

            if(!String.IsNullOrEmpty(personSearch))
            {
                listEN = listEN.Where(s => s.Personalidad.Contains(personSearch)).ToList();
            }

            if(!String.IsNullOrEmpty(usuSearch))
            {
                listEN = listEN.Where(s => s.Usuario.Email.Contains(usuSearch)).ToList();
            }

            switch (sortOrder)
            {
                case "aficion_desc":
                    listEN = listEN.OrderByDescending(s => s.AficionFavorita).ToList();
                    break;

                case "personalidad_desc":
                    listEN = listEN.OrderByDescending(s => s.Personalidad).ToList();
                    break;

                case "color_desc":
                    listEN = listEN.OrderByDescending(s => s.ColorFavorito).ToList();
                    break;
                case "usuario_desc":
                    listEN = listEN.OrderByDescending(s => s.Usuario.Email).ToList();
                    break;

                default:
                    listEN = listEN.OrderBy(s => s.Usuario.Email).ToList();
                    break;
            }

            IEnumerable<TestAnimalIdealViewModel> listView = new TestAnimalIdealAssembler().ConvertListENToModel(listEN).ToList();

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listView.ToPagedList(pageNumber, pageSize));
        }

        // GET: TestAnimalIdeal/Details/5
        public ActionResult Details(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            TestAnimalIdealViewModel test = null;
            TestAnimalIdealEN testEN = new TestAnimalIdealCAD(session).Ver_Resultado(id);
            test = new TestAnimalIdealAssembler().ConvertENToModelUI(testEN);

            SessionClose();

            return View(test);
        }

        public ActionResult VerResultado(int id)
        {
            SessionInitialize();

            TestAnimalIdealCAD testCAD = new TestAnimalIdealCAD(session);
            TestAnimalIdealCEN testCEN = new TestAnimalIdealCEN(testCAD);

            ViewData["IdTest"] = id;
            ViewData["NombreTest"] = testCEN.Ver_Resultado(id).Usuario.Nombre;

            TestAnimalIdealViewModel test = null;
            TestAnimalIdealEN testEN = new TestAnimalIdealCAD(session).Ver_Resultado(id);
            test = new TestAnimalIdealAssembler().ConvertENToModelUI(testEN);

            SessionClose();

            return View(test);
        }

        // GET: TestAnimalIdeal/Create
        public ActionResult Create()
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            IList<UsuarioEN> listausuarios = new UsuarioCEN().Dame_Todos(0, -1);
            IList<SelectListItem> usuariositems = new List<SelectListItem>();

            foreach (UsuarioEN usu in listausuarios)
            {
                usuariositems.Add(new SelectListItem { Text = usu.Nombre, Value = usu.Email });

            }

            ViewData["idUsuario"] = usuariositems;

            return View();
        }

        // POST: TestAnimalIdeal/Create
        [HttpPost]
        public ActionResult Create(TestAnimalIdealViewModel test)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add insert logic here
                TestAnimalIdealCEN testCEN = new TestAnimalIdealCEN();
                testCEN.Nuevo(test.idUsuario);

                TempData["mensajeModalTest"] = "Test creado correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalTest"] = "Ha habido un error al crear el test";
                return RedirectToAction("Index");
            }
        }

        // GET: TestAnimalIdeal/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            TestAnimalIdealViewModel test = null;
            TestAnimalIdealEN testEN = new TestAnimalIdealCAD(session).Ver_Resultado(id);
            test = new TestAnimalIdealAssembler().ConvertENToModelUI(testEN);

            SessionClose();

            return View(test);
        }

        // POST: TestAnimalIdeal/Edit/5
        [HttpPost]
        public ActionResult Edit(TestAnimalIdealViewModel test)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add update logic here
                TestAnimalIdealCEN testCEN = new TestAnimalIdealCEN();

                testCEN.Rellenar_Test(test.Id, test.AficionFavorita, test.Personalidad, test.ColorFavorito);

                TempData["mensajeModalTest"] = "Test editado correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalTest"] = "Ha habido un error al editar el test";
                return RedirectToAction("Index");
            }
        }

        // GET: TestAnimalIdeal/Edit/5
        public ActionResult RellenarTest()
        {

            return View();
        }

        // POST: TestAnimalIdeal/Edit/5
        [HttpPost]
        public ActionResult RellenarTest(TestAnimalIdealViewModel test)
        {
            try
            {
                // TODO: Add update logic here
                TestAnimalIdealCEN testCEN = new TestAnimalIdealCEN();

                UsuarioEN usuen = ((UsuarioEN)Session["Usuario"]);

                int idTest=testCEN.Nuevo(usuen.Email);

                testCEN.Rellenar_Test(idTest, test.AficionFavorita, test.Personalidad, test.ColorFavorito);

                return RedirectToAction("VerResultado", new { id = idTest });
            }
            catch
            {
                TempData["mensajeModalTest"] = "Ha habido un error al rellenar el test";
                return RedirectToAction("Index");
            }
        }

        // GET: TestAnimalIdeal/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            TestAnimalIdealCAD testCAD = new TestAnimalIdealCAD(session);

WebProtectoraMilpatitas/Views/TestAnimalIdeal/Create.cshtml
@model WebProtectoraMilpatitas.Models.TestAnimalIdealViewModel

@{
    ViewBag.Title = "Crear nuevo test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear nuevo Test Animal Ideal</h2>

@using (Html.BeginForm("Create", "TestAnimalIdeal", FormMethod.Post, new { @class = "formGuapo" })) 
{
    @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <p class="text">
            @Html.LabelFor(model => model.idUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
            
                @Html.DropDownListFor(model => model.idUsuario, ViewData["idUsuario"] as SelectList, "Selecciona un usuario")
          </p> 

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    
}

<div class="parrafoCentrar">
    <i class="fas fa-clipboard-list"></i> @Html.ActionLink("Volver a la lista", "Index")
</div>

WebProtectoraMilpatitas/Views/TestAnimalIdeal/Delete.cshtml
@model WebProtectoraMilpatitas.Models.TestAnimalIdealViewModel

@{
    ViewBag.Title = "Eliminar Test Animal Ideal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Test Animal Ideal</h2>
<div class="formEliminarGuapo">
    <h2>¿Estás seguro de que quieres eliminar el test @ViewData["IdTest"] de @ViewData["NombreTest"]?</h2>
</div>
<div>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color parrafoCentrar">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            <i class="fas fa-clipboard-list"></i> @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

WebProtectoraMilpatitas/Views/TestAnimalIdeal/Details.cshtml
@model WebProtectoraMilpatitas.Models.TestAnimalIdealViewModel

@{
    ViewBag.Title = "Detalles Test Animal Ideal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles Test Animal Ideal</h2>
<section id="secanim">
    <main id="details">
    <div class="detalleUsu">

        <hr />
        <p class="text">
            @Html.DisplayNameFor(model => model.AficionFavorita)
            @Html.DisplayFor(model => model.AficionFavorita)
        </p>
        <p class="text">
            @Html.DisplayNameFor(model => model.Personalidad)
            @Html.DisplayFor(model => model.Personalidad)
        </p>
        <p class="text">
            @Html.DisplayNameFor(model => model.ColorFavorito)

            @Html.DisplayFor(model => model.ColorFavorito)
        </p>
        <p class="text">
            @Html.DisplayNameFor(model => model.idUsuario)

            @Html.DisplayFor(model => model.idUsuario)
        </p>
        <p class="text">
            @Html.DisplayNameFor(model => model.Resultado)

            @Html.DisplayFor(model => model.Resultado)
        </p>


       </div>
    </main>
</section>
    <p class="parrafoCentrar">
        <i class="fas fa-pen"></i> @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
        <i class="fas fa-clipboard-list"></i> @Html.ActionLink("Volver a la lista", "Index")
    </p>

WebProtectoraMilpatitas/Views/TestAnimalIdeal/Edit.cshtml
@model WebProtectoraMilpatitas.Models.TestAnimalIdealViewModel

@{
    ViewBag.Title = "Editar Test Animal Ideal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Test Animal Ideal</h2>

@using (Html.BeginForm("Edit", "TestAnimalIdeal", FormMethod.Post, new { @class = "formNoTanGuapo" }))
{
    @Html.AntiForgeryToken()



    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <p class="text">
        @Html.LabelFor(model => model.AficionFavorita, htmlAttributes: new { @class = "control-label col-md-2" })

        @Html.EditorFor(model => model.AficionFavorita, new { htmlAttributes = new { @class = "form-control" } })
    </p>
    @Html.ValidationMessageFor(model => model.AficionFavorita, "", new { @class = "text-danger" })


    <p class="text">
    @Html.LabelFor(model => model.Personalidad, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.Personalidad, new { htmlAttributes = new { @class = "form-control" } })
    </p>
       @Html.ValidationMessageFor(model => model.Personalidad, "", new { @class = "text-danger" })


    <p class="text">
    @Html.LabelFor(model => model.ColorFavorito, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.ColorFavorito, new { htmlAttributes = new { @class = "form-control" } })
    </p>
    @Html.ValidationMessageFor(model => model.ColorFavorito, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Editar" class="btn btn-default" />
        </div>
    </div>

}

<div class="parrafoCentrar">
    <i class="fas fa-clipboard-list"></i> @Html.ActionLink("Volver a la lista", "Index")
</div>

WebProtectoraMilpatitas/Views/TestAnimalIdeal/RellenarTest.cshtml
@model WebProtectoraMilpatitas.Models.TestAnimalIdealViewModel

@{
    ViewBag.Title = "Rellenar Test";
    Layout = "~/Views/Shared/_LayoutUsu.cshtml";
}

<h2>Rellenar Test</h2>

@using (Html.BeginForm("RellenarTest", "TestAnimalIdeal", FormMethod.Post, new { @class = "formTestIdeal" }))
{
    @Html.AntiForgeryToken()


    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.LabelFor(model => model.AficionFavorita, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="form-group">
        <p class="textIdeal">
            <label>Animación</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/animacion.png" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Animacion")
        </p>

        <p class="textIdeal">
            <label>Astrología</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/astrologia.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Astrologia")

        </p>
        <p class="textIdeal">
            <label>Bailar</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/bailar.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Bailar")
        </p>
        <p class="textIdeal">
            <label>Cantar</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/cantar.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Cantar")
        </p>

        <p class="textIdeal">
            <label>Hacer deporte</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/deporte.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Hacer deporte")
        </p>
        <p class="textIdeal">
            <label>Dibujar</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/dibujar.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Dibujar")
        </p>
        <p class="textIdeal">
            <label>Leer</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/leer.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Leer")
        </p>
        <p class="textIdeal">
            <label>Manualidades</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Aficiones/manualidades.jpg" />

            @Html.RadioButtonFor(model => model.AficionFavorita, "Manualidades")
        </p>

    </div>
    @Html.LabelFor(model => model.Personalidad, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="form-group">

        <p class="textIdeal">
            <label>Agresiva</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/agresiva.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Agresiva")
        </p>
        <p class="textIdeal">
            <label>Alegre</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/alegre.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Alegre")
        </p>
        <p class="textIdeal">
            <label>Depresiva</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/depresiva.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Depresiva")
        </p>
        <p class="textIdeal">
            <label>Egocéntrica</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/egocentrica.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Egocentrica")
        </p>
        <p class="textIdeal">
            <label>Inteligente</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/inteligente.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Inteligente")
        </p>
        <p class="textIdeal">
            <label>Miedosa</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/miedosa.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Miedosa")
        </p>
        <p class="textIdeal">
            <label>Preocupada</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/preocupada.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Preocupada")
        </p>
        <p class="textIdeal">
            <label>Valiente</label>
            <img style="width: 100px;height: 100px;" src="~/Imagenes/Test/Personalidades/valiente.jpg" />

            @Html.RadioButtonFor(model => model.Personalidad, "Valiente")
        </p>

    </div>
    @Html.LabelFor(model => model.ColorFavorito, htmlAttributes: new { @class = "control-label col-md-2" })
<div class="form-group">

    <p class="textIdeal">
        <label>Amarillo</label>
        <img style="width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/amarillo.png" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Amarillo")
    </p>
    <p class="textIdeal">
        <label>Azul celeste</label>
        <img style="width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/azul-celeste.jpg" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Azul celeste")
    </p>
    <p class="textIdeal">
        <label>Marrón</label>
        <img style=" width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/marron.jpg" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Marron")
    </p>
    <p class="textIdeal">
        <label>Naranja</label>
        <img style="width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/naranja.png" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Naranja")
    </p>
    <p class="textIdeal">
        <label>Negro</label>
        <img style=" width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/negro.jpg" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Negro")
    </p>
    <p class="textIdeal">
        <label>Púrpura</label>
        <img style="width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/purpura.png" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Purpura")
    </p>
    <p class="textIdeal">
        <label>Rojo</label>
        <img style="width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/rojo.jpg" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Rojo")
    </p>
    <p class="textIdeal">
        <label>Verde</label>
        <img style="width: 75px;height: 75px;" src="~/Imagenes/Test/Colores/verde.png" />

        @Html.RadioButtonFor(model => model.ColorFavorito, "Verde")
    </p>

</div>

    <div class="form-group">
         <input type="submit" style="margin-left: auto;margin-right: auto;margin-top: 20px;" value="Rellenar" class="btn btn-default" />
    </div>

}

<div class="parrafoCentrar">
    <i class="fas fa-home"></i> @Html.ActionLink("Volver a inicio", "Index", "Home")
</div>

WebProtectoraMilpatitas/Views/TestAnimalIdeal/VerResultado.cshtml
@model WebProtectoraMilpatitas.Models.TestAnimalIdealViewModel

@{
    ViewBag.Title = "Ver Resultado";
    Layout = "~/Views/Shared/_LayoutUsu.cshtml";
}

<h2>Resultado del test @ViewData["IdTest"] del usuario @ViewData["NombreTest"]</h2>

<div>

    <hr />
    <main id="mainart">
        

            <h2 style="width: 100%">
                @Html.DisplayFor(model => model.Resultado)
            </h2>
            <p style="width: 100%;">
                @{
                    string foto = "";

                    if (Model.Resultado.Contains("perro"))
                    {
                        foto = "perro";
                    }
                    else
                    {
                        if (Model.Resultado.Contains("gato"))
                        {
                            foto = "gato";
                        }
                        else
                        {
                            if (Model.Resultado.Contains("pez"))
                            {
                                foto = "pez";
                            }
                            else
                            {
                                if (Model.Resultado.Contains("pajaro"))
                                {
                                    foto = "pajaro";
                                }
                                else
                                {
                                    if (Model.Resultado.Contains("tortuga"))
                                    {
                                        foto = "tortuga";
                                    }
                                    else
                                    {
                                        if (Model.Resultado.Contains("geco"))
                                        {
                                            foto = "geco";
                                        }
                                        else
                                        {
                                            if (Model.Resultado.Contains("conejo"))
                                            {
                                                foto = "conejo";
                                            }
                                            else
                                            {
                                                if (Model.Resultado.Contains("hamster"))
                                                {
                                                    foto = "hamster";
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    string ruta = "";
                    ruta = @"Imagenes/Test/Resultado/" + foto + ".jpg";
                    <img style="display:block; margin:auto;" src=~/@ruta />
                }
            </p>
            

        
    </main>
</div>
<p class="parrafoCentrar">
    <i class="fas fa-home"></i> @Html.ActionLink("Volver a inicio", "Index", "Home")
</p>