WebProtectoraMilpatitas/Models/SolicitudAdopcionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebProtectoraMilpatitas.Models
{
    public class SolicitudAdopcionViewModel
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }

        [Display(Prompt = "Nombre del solicitante", Description = "Nombre del solicitante", Name = "Nombre")]
        [Required(ErrorMessage = "Debe indicar un nombre para el solicitante")]
        [StringLength(maximumLength: 50, ErrorMessage = "El nombre del solicitante no puede superar los 50 caracteres")]

        public String Nombre { get; set; }

        [Display(Prompt = "Animales a cargo", Description = "Animales a cargo", Name = "¿Cuantos animales tienes a cargo?")]
        [Required(ErrorMessage = "Debe indicar los animales que tiene a cargo")]
        [Range(minimum: 0, maximum: 12, ErrorMessage = "El número de animales tiene que estar entre 0 y 12")]

        public int AnimalesAcargo { get; set; }

        [Display(Prompt = "AmbienteConvivencia", Description = "Ambiente de convivencia", Name = "¿Cómo describirias el ambiente convivencia en tu casa?")]
        [Required(ErrorMessage = "Debe indicar un ambiente de convivencia")]
        [StringLength(maximumLength: 100, ErrorMessage = "La descripción no puede superar los 100 caracteres")]

        public String AmbienteConvivencia { get; set; }

        [Display(Prompt = "TiempoLibre", Description = "Tiempo libre al día para dedicar al animal", Name = "¿Cuantas horas libres tienes al día? (indicar número en horas)")]
        [Required(ErrorMessage = "Debe indicar un número de horas")]
        [Range(minimum: 0, maximum: 24, ErrorMessage = "El número de horas libres al día tiene que estar entre 0 y 24 horas ")]

        public int TiempoLibre { get; set; }

        [Display(Prompt = "TodosAcuerdo", Description = "Todos están de acuerdo", Name = "¿Estan todos de acuerdo en casa? (marca la casilla si es asi)")]
        [Required(ErrorMessage = "Debe indicar si están todos de acuerdo o no")]

        public Boolean TodosAcuerdo { get; set; }

        [Display(Prompt = "MotivosAdopcion", Description = "Motivos de la adopción", Name = "¿Que motivos te han llevado a querer adoptar a este animal?")]
        [Required(ErrorMessage = "Debe indicar un motivo mínimo para adoptar")]
        [StringLength(maximumLength: 300, ErrorMessage = "La descripción del motivo no puede superar los 300 caracteres")]

        public String MotivosAdopcion { get; set; }


        [Display(Prompt = "Estado de solicitud", Description = "Estado de solicitud animal", Name = "Estado de solicitud")]
        [Required(ErrorMessage = "Debe indicar un estado de solicitud de animal")]

        public ProtectoraMilpatitasGenNHibernate.Enumerated.ProtectoraMilpatitas.EstadoAdopcionEnum Estado { get; set; }

        [ScaffoldColumn(false)]

        [Display(Prompt = "Usuario solicitante", Description = "Usuario que solicita adopción", Name = "Usuario")]

        public string idUsuario { get; set; }

        [Display(Prompt = "Nombre del usuario", Description = "Nombre del usuario", Name = "Usuario")]
        public string NomUsuario { get; set; }

        [Display(Prompt = "Foto del usuario", Description = "Foto del usuario", Name = "FotoUsuario")]

        public String FotoUsuario { get; set; }


        [ScaffoldColumn(false)]

        [Display(Prompt = "Animal Solicitado", Description = "Animal que solicitan en adopción", Name = "Animal")]

        public int idAnimal { get; set; }

        [Display(Prompt = "Nombre del animal", Description = "Nombre del animal", Name = "Animal solicitado")]
        public string NomAnimal { get; set; }

        [Display(Prompt = "Foto del animal", Description = "Foto del animal", Name = "FotoAnimal")]

        public String FotoAnimal { get; set; }


        [Display(Prompt = "Fecha solicitud", Description = "Fecha solicitud", Name = "Fecha solicitud")]
        public DateTime FechaSoli { get; set; }

        [ScaffoldColumn(false)]
        public int idContrato { get; set; }


    }
}

WebProtectoraMilpatitas/Controllers/SolicitudAdopcionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ProtectoraMilpatitasGenNHibernate.CAD.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CP.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
using WebProtectoraMilpatitas.Assemblers;
using WebProtectoraMilpatitas.Models;

namespace WebProtectoraMilpatitas.Controllers
{
    [Authorize]
    public class SolicitudAdopcionController : BasicController
    {
        public ActionResult Index(int? page, string sortOrder, string nameSearch, string usuSearch, string aniSearch, string dateSearch, string estSearch)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            SolicitudAdopcionCAD solCAD = new SolicitudAdopcionCAD(session);
            SolicitudAdopcionCEN solCEN = new SolicitudAdopcionCEN(solCAD);

            IList<SolicitudAdopcionEN> solsEN = solCEN.Dame_Todas(0, -1).Where(s=>s.Estado!=ProtectoraMilpatitasGenNHibernate.Enumerated.ProtectoraMilpatitas.EstadoAdopcionEnum.rechazado).ToList();

            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.UsuSort = String.IsNullOrEmpty(sortOrder) ? "usu_desc" : "";
            ViewBag.AniSort = String.IsNullOrEmpty(sortOrder) ? "ani_desc" : "";
            ViewBag.DateSort = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.EstSort = String.IsNullOrEmpty(sortOrder) ? "est_desc" : "";

            if (!String.IsNullOrEmpty(nameSearch))
            {
                solsEN = solsEN.Where(s => s.Nombre.Contains(nameSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(usuSearch))
            {
                solsEN = solsEN.Where(s => s.Usuario.Nombre.Contains(usuSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(aniSearch))
            {
                solsEN = solsEN.Where(s => s.Animal.Nombre.Contains(aniSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(estSearch))
            {
                solsEN = solsEN.Where(s => s.Estado.ToString().Contains(estSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(dateSearch))
            {
                solsEN = solsEN.Where(s => s.FechaSolicitud.ToString().Contains(dateSearch)).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    solsEN = solsEN.OrderByDescending(s => s.Nombre).ToList();
                    break;
                case "usu_desc":
                    solsEN = solsEN.OrderByDescending(s => s.Usuario.Nombre).ToList();
                    break;
                case "ani_desc":
                    solsEN = solsEN.OrderByDescending(s => s.Animal.Nombre).ToList();
                    break;
                case "Date":
                    solsEN = solsEN.OrderBy(s => s.FechaSolicitud).ToList();
                    break;
                case "date_desc":
                    solsEN = solsEN.OrderByDescending(s => s.FechaSolicitud).ToList();
                    break;
                case "est_desc":
                    solsEN = solsEN.OrderByDescending(s => s.Estado).ToList();
                    break;
                default:
                    solsEN = solsEN.OrderBy(s => s.Nombre).ToList();
                    break;
            }

            IEnumerable<SolicitudAdopcionViewModel> listaSolicitudes = new SolicitudAdopcionAssembler().ConvertListENToModel(solsEN).ToList();

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listaSolicitudes.ToPagedList(pageNumber, pageSize));
        }

        // GET: SolicitudAdopcion/Details/5
        public ActionResult Details(int id)
        {
            SolicitudAdopcionViewModel sol = null;

            SessionInitialize();

            SolicitudAdopcionEN solEN = new SolicitudAdopcionCAD(session).Ver_Solicitud(id);

            sol = new SolicitudAdopcionAssembler().ConvertENToModelUI(solEN);

            SessionClose();

            return View(sol);
        }

        // GET: SolicitudAdopcion/Create
        public ActionResult Create()
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            IList<UsuarioEN> listausuarios = new UsuarioCEN().Dame_Todos(0, -1);
            IList<SelectListItem> usuariositems = new List<SelectListItem>();

            foreach (UsuarioEN usu in listausuarios)
            {
                usuariositems.Add(new SelectListItem { Text = usu.Nombre, Value = usu.Email });

            }

            ViewData["idUsuario"] = usuariositems;

            IList<AnimalEN> listaAnimales = new AnimalCEN().Dame_Todos(0, -1);
            IList<SelectListItem> animalesItems = new List<SelectListItem>();

            foreach (AnimalEN ani in listaAnimales)
            {
                animalesItems.Add(new SelectListItem { Text = ani.Nombre, Value = ani.Id.ToString() });
            }

            ViewData["idAnimal"] = animalesItems;

            return View();
        }

        // POST: SolicitudAdopcion/Create
        [HttpPost]
        public ActionResult Create(SolicitudAdopcionViewModel sol)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add insert logic here
                SolicitudAdopcionCEN soliCEN = new SolicitudAdopcionCEN();

                int idsol=soliCEN.Nuevo(sol.idUsuario, sol.idAnimal, DateTime.Today);

                SolicitudAdopcionCP solCP = new SolicitudAdopcionCP();
                solCP.Actualizar_Estado(idsol, ProtectoraMilpatitasGenNHibernate.Enumerated.ProtectoraMilpatitas.EstadoAdopcionEnum.enEspera);

                TempData["mensajeModal"] = "¡Enhorabuena! Has creado una solicitud";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModal"] = "Ha habido un error al crear la solicitud";
                return RedirectToAction("Index");
            }
        }

        // GET: SolicitudAdopcion/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SolicitudAdopcionViewModel sol = null;

            SessionInitialize();

            SolicitudAdopcionEN solEN = new SolicitudAdopcionCAD(session).Ver_Solicitud(id);

            sol = new SolicitudAdopcionAssembler().ConvertENToModelUI(solEN);

            SessionClose();

            return View(sol);
           
        }

        // POST: SolicitudAdopcion/Edit/5
        [HttpPost]
        public ActionResult Edit(SolicitudAdopcionViewModel sol)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add update logic here
               
                SolicitudAdopcionCEN solCEN = new SolicitudAdopcionCEN();

                solCEN.Rellenar_Solicitud(sol.Id, sol.Nombre, sol.AnimalesAcargo,
                    sol.AmbienteConvivencia, sol.TiempoLibre, sol.TodosAcuerdo, sol.MotivosAdopcion);

                TempData["mensajeModal"] = "¡Enhorabuena! Has modificado la información de la solicitud";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModal"] = "Ha habido un error al editar la solicitud";
                return RedirectToAction("Index");
            }
        }

        public ActionResult ActualizarEstado(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SolicitudAdopcionViewModel sol = null;

            SessionInitialize();

            SolicitudAdopcionEN solEN = new SolicitudAdopcionCAD(session).Ver_Solicitud(id);

            sol = new SolicitudAdopcionAssembler().ConvertENToModelUI(solEN);

            SessionClose();

            return View(sol);

        }

        // POST: SolicitudAdopcion/Edit/5
        [HttpPost]
        public ActionResult ActualizarEstado(SolicitudAdopcionViewModel sol)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }

WebProtectoraMilpatitas/Views/SolicitudAdopcion/AceptarSolicitud.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "AceptarSolicitud";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Aceptar Solicitud</h2>

<div id="mainart">
    <h2>¿Estás seguro de querer aceptar la solicitud de adopcion @ViewData["idSol"] de @ViewData["idUsu"] para el animal @ViewData["idAni"]?</h2>
    <div style="margin-left: auto; margin-right: auto;">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color parrafoCentrar">
                <input type="submit" value="Aceptar" class="btn btn-default" /> |
                <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
            </div>
        }
    </div>
</div>

WebProtectoraMilpatitas/Views/SolicitudAdopcion/ActualizarEstado.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "ActualizarEstado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Actualizar Estado Solicitud</h2>


@using (Html.BeginForm("ActualizarEstado", "SolicitudAdopcion", FormMethod.Post, new { @class = "formNoTanGuapo" }))
{
    @Html.AntiForgeryToken()
    

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<p class="text">
    @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
    
    @Html.EnumDropDownListFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
    
</p>
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    
}

<div class="parrafoCentrar">
    <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebProtectoraMilpatitas/Views/SolicitudAdopcion/Create.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "Crear nueva Solicitud de Adopcion";
}

<h2>Crear nueva Solicitud de Adopcion</h2>


@using (Html.BeginForm("Create", "SolicitudAdopcion", FormMethod.Post, new { @class = "formGuapo" })) 
{
    @Html.AntiForgeryToken()
    

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
    <p class="text">
        @Html.LabelFor(model => model.idUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
        
            @Html.DropDownListFor(model => model.idUsuario, ViewData["idUsuario"] as SelectList, "Selecciona un usuario")
    </p>

    <p class="text">
        @Html.LabelFor(model => model.idAnimal, htmlAttributes: new { @class = "control-label col-md-2" })
        
            @Html.DropDownListFor(model => model.idAnimal, ViewData["idAnimal"] as SelectList, "Selecciona un animal")
    </p>    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>

}

<div class="parrafoCentrar">
    <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebProtectoraMilpatitas/Views/SolicitudAdopcion/Delete.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "Eliminar Solicitud de Adopcion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Solicitud de Adopcion</h2>
<div class="formEliminarGuapo">
    <h2>¿Estás seguro de que quieres eliminar la solicitud @ViewData["IdSol"] de @ViewData["NombreSol"]?</h2>
</div>

<div>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color parrafoCentrar">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

WebProtectoraMilpatitas/Views/SolicitudAdopcion/Details.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel
@using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;

@{
    ViewBag.Title = "Detalles de la Solicitud de Adopcion";

    if (Session["Usuario"] != null)
    {
        if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutUsu.cshtml";
        }
    }
}

<h2>Detalles de la Solicitud de Adopcion</h2>
<section id="secanim">
    <main id="details">
        <article class="detalle">

            <div>
                <h2>


                    @Html.DisplayFor(model => model.Nombre)
                </h2>

                <p>
                    <b>@Html.DisplayNameFor(model => model.NomUsuario)</b>

                    @Html.DisplayFor(model => model.NomUsuario)
                </p>

                <p>


                    <img style="display:block;margin:auto; width: 200px;height: 200px;" border-radius: 80%; src="/@Html.DisplayFor(model => model.FotoUsuario)" />
                </p>

                <h2>




                    @Html.DisplayFor(model => model.NomAnimal)
                </h2>



                <p>
                    <img style="display:block;margin:auto; width: 200px;height: 200px;" border-radius: 80%; src="/@Html.DisplayFor(model => model.FotoAnimal)" />
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.AnimalesAcargo)</b>

                    @Html.DisplayFor(model => model.AnimalesAcargo)
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.AmbienteConvivencia)</b>

                    @Html.DisplayFor(model => model.AmbienteConvivencia)
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.TiempoLibre)</b>

                    @Html.DisplayFor(model => model.TiempoLibre)
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.TodosAcuerdo)</b>

                    @Html.DisplayFor(model => model.TodosAcuerdo)
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.MotivosAdopcion)</b>

                    @Html.DisplayFor(model => model.MotivosAdopcion)
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.Estado)</b>

                    @Html.DisplayFor(model => model.Estado)
                </p>

                <p>
                    <b>@Html.DisplayNameFor(model => model.FechaSoli)</b>

                    @Html.DisplayFor(model => model.FechaSoli)
                </p>

            </div>
            <div class="parrafoCentrar">
                @if (Session["Usuario"] != null)
                {
                    if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                    {
                        <p><i class="fas fa-thumbs-up"></i> @Html.ActionLink("Aceptar solicitud", "AceptarSolicitud", new { idSol = Model.Id, idUsu = Model.idUsuario, idAni = Model.NomAnimal })</p>
                        <p><i class="fas fa-thumbs-down"></i> @Html.ActionLink("Rechazar solicitud", "RechazarSolicitud", new { idSol = Model.Id, idUsu = Model.idUsuario, idAni = Model.NomAnimal })</p>




                        <p><i class="fas fa-pen"></i> @Html.ActionLink("Editar", "Edit", new { id = Model.Id })</p>
                    }
                }
                <p>
                    @{

                        if (Session["Usuario"] != null)
                        {
                            if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                            {
                                <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
                            }
                            else
                            {
                                <i class="fas fa-id-badge"></i> @Html.ActionLink("Volver a perfil", "Perfil", "Usuario", new { email = ((UsuarioEN)Session["Usuario"]).Email }, htmlAttributes: null)
                            }
                        }
                    }
                </p>
            </div>
        </article>
    </main>
</section>

WebProtectoraMilpatitas/Views/SolicitudAdopcion/Edit.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "Editar Solicitud de adopcion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Solicitud de adopcion</h2>


@using (Html.BeginForm("Edit", "SolicitudAdopcion", FormMethod.Post, new { @class = "formIncreible" }))
{
    @Html.AntiForgeryToken()
    
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<p class="notext">
    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
</p>
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
<p class="notext">
    @Html.LabelFor(model => model.AnimalesAcargo, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.AnimalesAcargo, new { htmlAttributes = new { @class = "form-control" } })
</p>
                @Html.ValidationMessageFor(model => model.AnimalesAcargo, "", new { @class = "text-danger" })

<p class="notext">
    @Html.LabelFor(model => model.AmbienteConvivencia, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.AmbienteConvivencia, new { htmlAttributes = new { @class = "form-control" } })
</p>
                @Html.ValidationMessageFor(model => model.AmbienteConvivencia, "", new { @class = "text-danger" })
<p class="notext">
    @Html.LabelFor(model => model.TiempoLibre, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.TiempoLibre, new { htmlAttributes = new { @class = "form-control" } })
</p>
                @Html.ValidationMessageFor(model => model.TiempoLibre, "", new { @class = "text-danger" })

<p class="notext">
    @Html.LabelFor(model => model.TodosAcuerdo, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <div class="checkbox">
            @Html.EditorFor(model => model.TodosAcuerdo)<br />
            @Html.ValidationMessageFor(model => model.TodosAcuerdo, "", new { @class = "text-danger" })
        </div>
    </div>
</p>

<p class="notext">
    @Html.LabelFor(model => model.MotivosAdopcion, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.MotivosAdopcion, new { htmlAttributes = new { @class = "form-control" } })
</p>
                @Html.ValidationMessageFor(model => model.MotivosAdopcion, "", new { @class = "text-danger" })


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-default" />
            </div>
        </div>

}

<div class="parrafoCentrar">
    <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebProtectoraMilpatitas/Views/SolicitudAdopcion/RechazarSolicitud.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "RechazarSolicitud";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Rechazar Solicitud</h2>

<h3>¿Estás seguro de querer rechazar la solicitud de adopcion @ViewData["idSol"] de @ViewData["idUsu"] para el animal @ViewData["idAni"]?</h3>
<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color parrafoCentrar">
            <input type="submit" value="Rechazar" class="btn btn-default" /> |
            <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

WebProtectoraMilpatitas/Views/SolicitudAdopcion/RechazarTodasSolicitud.cshtml
@model WebProtectoraMilpatitas.Models.SolicitudAdopcionViewModel

@{
    ViewBag.Title = "RechazarSolicitudes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Rechazar Solicitudes</h2>

<h3>¿Estás seguro de querer rechazar todas las solicitudes?</h3>
<div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color parrafoCentrar">
            <input type="submit" value="Rechazar" class="btn btn-default" /> |
            <i class="fas fa-edit"></i> @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>