WebProtectoraMilpatitas/Models/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebProtectoraMilpatitas.Models
{
    public class UsuarioViewModel : RegisterViewModel
    {
        
        [Display(Prompt = "Nombre del usuario", Description = "Nombre de usuario", Name = "Nombre")]
        [Required(ErrorMessage = "Debe usar un nombre de usuario")]
        //preguntar como poner un rango minimo en string
        [StringLength(maximumLength: 20, ErrorMessage = "El nombre tiene que tener entre 8 y 20 caracteres")]
        public string Nombre { get; set; }

     //   [Display(Prompt = "Foto de perfil", Description = "Foto de perfil", Name = "foto")]
       // [Required(ErrorMessage = "Debe seleccionar una foto para el perfil del usuario")]


        public String Foto { get; set; }
    }
}

WebProtectoraMilpatitas/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ProtectoraMilpatitasGenNHibernate.CAD.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CP.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
using WebProtectoraMilpatitas.Assemblers;
using WebProtectoraMilpatitas.Models;

namespace WebProtectoraMilpatitas.Controllers
{
    public class AnimalController : BasicController
    {
        [Authorize]
        //GET: Animal
        public ActionResult Index(int? page, string sortOrder, string nameSearch, string edadSearch, string sexoSearch, string centroSearch, string caracterSearch, string estSearch, string espSearch, string razSearch)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            AnimalCAD animalCAD = new AnimalCAD(session);
            AnimalCEN animalCEN = new AnimalCEN(animalCAD);
            IList<AnimalEN> listaAnimal = animalCEN.Dame_Todos(0, -1);

            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.EdadSort = String.IsNullOrEmpty(sortOrder) ? "edad_desc" : "";
            ViewBag.SexoSort = String.IsNullOrEmpty(sortOrder) ? "sexo_desc" : "";
            ViewBag.CentroSort = String.IsNullOrEmpty(sortOrder) ? "centro_desc" : "";
            ViewBag.CaracterSort = String.IsNullOrEmpty(sortOrder) ? "carac_desc" : "";
            ViewBag.EstadoSort = String.IsNullOrEmpty(sortOrder) ? "est_desc" : "";
            ViewBag.EspecieSort = String.IsNullOrEmpty(sortOrder) ? "esp_desc" : "";
            ViewBag.RazaSort = String.IsNullOrEmpty(sortOrder) ? "raz_desc" : "";

            if (!String.IsNullOrEmpty(nameSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Nombre.Contains(nameSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(edadSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Edad.ToString() == edadSearch).ToList();
            }

            if (!String.IsNullOrEmpty(sexoSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Sexo.ToString() == sexoSearch).ToList();
            }

            if (!String.IsNullOrEmpty(centroSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Centro.Contains(centroSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(caracterSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Caracter.Contains(caracterSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(estSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.DatosMedicos.ToString().Contains(estSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(espSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Especie.Nombre.Contains(espSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(razSearch))
            {
                listaAnimal = listaAnimal.Where(s => s.Raza.Nombre.Contains(razSearch)).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Nombre).ToList();
                    break;
                case "edad_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Edad).ToList();
                    break;
                case "sexo_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Sexo).ToList();
                    break;
                case "centro_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Centro).ToList();
                    break;
                case "carac_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Caracter).ToList();
                    break;
                case "est_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.EstadoAdopcion).ToList();
                    break;
                case "esp_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Especie.Nombre).ToList();
                    break;
                case "raz_desc":
                    listaAnimal = listaAnimal.OrderByDescending(s => s.Raza.Nombre).ToList();
                    break;
                default:
                    listaAnimal = listaAnimal.OrderBy(s => s.Nombre).ToList();
                    break;
            }

            IEnumerable<AnimalViewModel> listaView = new AnimalAssembler().ConvertListENToModel(listaAnimal).ToList();

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listaView.ToPagedList(pageNumber,pageSize));
        }

        [Authorize]
        // GET: /AnimalViewModels/ObtenerAnimalesPorEspecie/5
        public ActionResult ObtenerAnimalesPorEspecie(int p_especie, int? page)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            AnimalCAD aniCad = new AnimalCAD(session);
            EspecieCAD espeCad = new EspecieCAD(session);
            AnimalCEN aniCEN = new AnimalCEN(aniCad);
            IList<AnimalEN> listAni = aniCEN.Dame_Animales_Por_Especie(p_especie);
            IEnumerable<AnimalViewModel> listAni2 = new AnimalAssembler().ConvertListENToModel(listAni).ToList();
            EspecieEN espEN = espeCad.Dame_Por_Id(p_especie);

            ViewData["idEspecie"] = p_especie;

            if(espEN != null)
            {
                ViewData["NombreEspecie"] = espEN.Nombre;
            }

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listAni2.ToPagedList(pageNumber, pageSize));
        }

        [Authorize]
        public ActionResult ObtenerAnimalesPorUsuario(string email, int? page)
        {
            SessionInitialize();

            AnimalCAD aniCad = new AnimalCAD(session);
            UsuarioCAD usuCad = new UsuarioCAD(session);

            AnimalCEN aniCEN = new AnimalCEN(aniCad);
            UsuarioCEN usuCEN = new UsuarioCEN(usuCad);

            UsuarioEN usuEN = usuCEN.Dame_Por_Email(email);

            IList<AnimalEN> listAni = aniCEN.Obtener_Animal_Usuario(usuEN.Email);
            IEnumerable<AnimalViewModel> listAni2 = new AnimalAssembler().ConvertListENToModel(listAni).ToList();

            ViewData["NombreUsu"] = usuEN.Nombre;

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listAni2.ToPagedList(pageNumber, pageSize));
        }

        // GET: Animal/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            EspecieCAD espeCad = new EspecieCAD(session);
            AnimalViewModel ani = null;
            AnimalEN artEN = new AnimalCAD(session).Ver_Detalle_Animal(id);
            ani = new AnimalAssembler().ConvertENToModelUI(artEN);

            EspecieEN espEN = espeCad.Dame_Por_Id(ani.idEspecie);

            if (espEN != null)
            {
                ViewData["NombreEsp"] = espEN.Nombre;
            }


            SessionClose();
            return View(ani);
        }

        [Authorize]
        // GET: Animal/Create
        public ActionResult Create()
        {

           if (Session["Usuario"] != null) {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
           }

            IList<EspecieEN> listaEspecies = new EspecieCEN().Dame_Todas(0, -1);
            IList<SelectListItem> especiesItems = new List<SelectListItem>();

            foreach (EspecieEN esp in listaEspecies)
            {
                especiesItems.Add(new SelectListItem { Text=esp.Nombre, Value=esp.Id.ToString()});
            }

            ViewData["idEspecie"] = especiesItems;

            IList<RazaEN> listaRazas = new RazaCEN().Dame_Todas(0, -1);
            IList<SelectListItem> razasItems = new List<SelectListItem>();

            foreach(RazaEN raz in listaRazas)
            {
                razasItems.Add(new SelectListItem { Text = raz.Nombre, Value = raz.Id.ToString() });
            }

            ViewData["idRaza"] = razasItems;

            return View();
        }

        [Authorize]
        // POST: Animal/Create
        [HttpPost]
        public ActionResult Create(AnimalViewModel ani, HttpPostedFileBase file)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            string filename = "";
            string ruta = "";
            if (file != null && file.ContentLength > 0)
            {

                filename = Path.GetFileName(file.FileName);
                ruta = Path.Combine(Server.MapPath("~/Imagenes/animales/"), filename);
                file.SaveAs(ruta);

WebProtectoraMilpatitas/Controllers/MensajeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ProtectoraMilpatitasGenNHibernate.CAD.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CP.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
using WebProtectoraMilpatitas.Assemblers;
using WebProtectoraMilpatitas.Models;

namespace WebProtectoraMilpatitas.Controllers
{
    public class MensajeController:BasicController
    {
        public ActionResult Index(string email)
        {
            

            SessionInitialize();
            AdministradorCAD admiCAD = new AdministradorCAD(session);
            AdministradorCEN adminiCEN = new AdministradorCEN(admiCAD);
            

            IList<AdministradorEN> administradores = adminiCEN.Dame_Todos(0, -1);
            AdministradorEN admin = administradores[0];
            UsuarioEN usuen = new UsuarioEN();

            if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
            {
                UsuarioCAD usuarioCAD = new UsuarioCAD(session);
                
                   IList<UsuarioEN> usuarios = usuarioCAD.Dame_Todos(0,-1);
                foreach(UsuarioEN usu in usuarios)
                {
                    if (usu.Email.Equals(email))
                    {
                        usuen = usu;
                    }
                }

                
                TempData["emailUsu"] = email;

            }
            else {

              usuen = ((UsuarioEN)Session["Usuario"]);
            }
           

            MensajeCAD menCAD = new MensajeCAD(session);
            MensajeCEN menCEN = new MensajeCEN(menCAD);

            IList<MensajeEN> todos = menCEN.Dame_Todos(0, -1);

            IList<MensajeEN> mensajesUsu = new List<MensajeEN>();
            IList<MensajeEN> mensajesAdmin = new List<MensajeEN>();

            if (todos.Count>0)
            {
                //me quedo con los mensajes que ha enviado el usuario
                mensajesUsu = todos.Where(s => s.Enviador == usuen.Nombre).ToList();

                //me quedo con los mensajes que ha enviado el administrador
                //luego me quedo con los que ha enviado al usuario del chat
                mensajesAdmin = todos.Where(s => s.Enviador == admin.Nombre).ToList();
                mensajesAdmin = mensajesAdmin.Where(s => s.Usuario.Email == usuen.Email).ToList();
            }
            
            IList<MensajeEN> mensajes= new List<MensajeEN>();
            
            if (mensajesAdmin.Count > 0 )
            {
                foreach (MensajeEN men in mensajesAdmin)
                {
                    mensajesUsu.Add(men);
                }
                 mensajes = mensajesUsu;
            }
            else if (mensajesUsu.Count > 0)
            {
                foreach (MensajeEN men in mensajesUsu)
                {
                    mensajesAdmin.Add(men);
                }
                mensajes = mensajesAdmin;
            }

            IEnumerable<MensajeEN> mensajesOrden = mensajes.OrderBy(f => f.Fecha);
            IList<MensajeEN> sortedList = mensajesOrden.ToList();

            IEnumerable<MensajeViewModel> listaMensajes = new MensajeAssembler().ConvertListENToModel(sortedList).ToList();

            SessionClose();          

            return View(listaMensajes);
        }

        public ActionResult Create()
        {

            return View();

        }

        // POST: Seguimiento/Create
        [HttpPost]
        public ActionResult Create(MensajeViewModel mensa)
        {
          

            try
            {
                // TODO: Add insert logic here
                SessionInitialize();
                MensajeCP menCP = new MensajeCP();

                UsuarioEN usuen = ((UsuarioEN)Session["Usuario"]);

                AdministradorCAD admiCAD = new AdministradorCAD(session);
                AdministradorCEN adminiCEN = new AdministradorCEN(admiCAD);

                IList<AdministradorEN> administradores = adminiCEN.Dame_Todos(0, -1);
                AdministradorEN admin = administradores[0];

                //si el usuario de la sesion es el admin, hay que obtener los datos del usuario del chat para pasar el email
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {
                    menCP.Nuevo(admin.Email, (string)TempData["emailUsu"], mensa.Texto, DateTime.Now, usuen.Nombre);
                }
                else
                {
                    menCP.Nuevo(admin.Email, usuen.Email, mensa.Texto, DateTime.Now, usuen.Nombre);
                }


                TempData["mensajeModal"] = "Mensaje enviado con exito";

                SessionClose();
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {
                    return RedirectToAction("Index", new { email = (string)TempData["emailUsu"] });
                }

                    return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModal"] = "Ha habido un error al enviar el mensaje";
                return RedirectToAction("Index");
            }
        }

        public ActionResult Delete(int id)
        {
          
            return View();
        }

        // POST: Especie/Delete/5
        [HttpPost]
        public ActionResult Delete(MensajeViewModel men)
        {
            

            try
            {
                // TODO: Add delete logic here
                MensajeCEN mensajeCEN = new MensajeCEN();
                mensajeCEN.Eliminar(men.Id);

                TempData["mensajeModal"] = "Mensaje eliminado correctamente";
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {
                    return RedirectToAction("Index", new { email = (string)TempData["emailUsu"] });
                }
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModal"] = "Ha habido un error al eliminar el mensaje";
                return RedirectToAction("Index");
            }
        }
    }
}

WebProtectoraMilpatitas/Views/Usuario/Create.cshtml
@model WebProtectoraMilpatitas.Models.UsuarioViewModel

@{
    ViewBag.Title = "Crear nuevo usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/codigo.js"></script>
<h2>Crear Usuario</h2>


@using (Html.BeginForm("Create", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="editor-label">
        @Html.LabelFor(model => model.Foto)
    </div>
    <div class="editor-field">
        <label for="foto"><img style="width:200px;height:200px;" src="~/Imagenes/usuarios/imagen.png" /></label>
        <input onchange="cargarFoto(this);" style="display:none;" id="foto" type="file" name="file" />
        <p><label for="foto">Buscar Foto</label></p>
        @Html.ValidationMessageFor(model => model.Foto)
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <i class="fas fa-user"></i> @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebProtectoraMilpatitas/Views/Usuario/Delete.cshtml
@model ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas.UsuarioCEN

@{
    ViewBag.Title = "Eliminar usuario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar usuario</h2>
<div class="formEliminarGuapo">
    <h2>¿Estás seguro de querer eliminar al usuario @ViewData["NombreUsu"]?</h2>
</div>
<div>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color parrafoCentrar">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            <i class="fas fa-user"></i> @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

WebProtectoraMilpatitas/Views/Usuario/Index.cshtml
@model PagedList.IPagedList<WebProtectoraMilpatitas.Models.UsuarioViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "ProtectoraMilPatitas-Administrador: Usuarios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@if (((string)TempData["mensajeModal"]) != null)
{
    <div id="capafondo">
        <!--  <script>"mensajeModal();"</script> -->
        <article id="ar">
            <h2>Usuario</h2>
            <p>
                @((string)TempData["mensajeModal"])
            </p>

            <footer><button class="button" onclick="cerrarMensajeModal();">cerrar</button></footer>
        </article>
    </div>


}

<h2>Filtrar usuarios por: </h2>
<div class="readFilters" style="margin-right: auto;margin-left: auto;">
    <ul class="readFiltersUls">
        <li>
            @using (Html.BeginForm())
            {
            <p>
                <label class="textLabel"> Nombre: </label>
                <label class="searchPoner">
                    @Html.TextBox("nameSearch")<input style="display:none;" id="buscNombreUsu" type="submit" value="Buscar" />
                    <label for="buscNombreUsu" style="margin-left: 10px;" class="fas fa-search"></label>
                </label>
            </p>
            }
        </li>
    </ul>
</div>   
<h2>Ordenar usuarios por:</h2>
<div class="enlacesOrdenar">
    <h3 style="margin-left: auto;margin-right: auto;">@Html.ActionLink("Ordenar por Nombre", "Index", new { sortOrder = ViewBag.NameSort })</h3>
</div>
            <h2>Usuarios</h2>

            <main id="mainart">
                @{
                    if (Model.Any()) { 

                    foreach (var item in Model)
                    {

                        <article class="articulos">
                            @if (item.Nombre != null && !item.Nombre.Equals(""))
                            {
                                <h2 class="titleUsus">@Html.DisplayFor(modelItem => item.Nombre)</h2>
                            }
                            else
                            {
                                <h2 class="titleUsus">  @Html.DisplayFor(modelItem => item.Nombre);</h2>
                            }
                            <div style="display: block;margin: auto;">
                                <img style="display: block;margin: auto;" src="/@Html.DisplayFor(modelItem => item.Foto)" />
                            </div>
                            <div>
                                <p><i class="fas fa-info"></i> @Html.ActionLink("Detalles", "Details", new { email = item.Email })</p>
                                <p><i class="fas fa-comment-dots"></i> @Html.ActionLink("Chatear con Usuario", "Index", "Mensaje", new { email = item.Email }, htmlAttributes: null)</p>
                                <p><i class="fas fa-edit"></i> @Html.ActionLink("Obtener Solicitudes", "ObtenerSolicitudUsuario", "SolicitudAdopcion", new { email = item.Email }, htmlAttributes: null)</p>
                                <p><i class="fas fa-file-signature"></i> @Html.ActionLink("Obtener Contratos", "ObtenerContratoUsuario", "ContratoAdopcion", new { email = item.Email }, htmlAttributes: null)</p>
                                <p><i class="fas fa-eye"></i> @Html.ActionLink("Obtener Seguimientos", "ObtenerSeguimientoUsuario", "Seguimiento", new { email = item.Email }, htmlAttributes: null)</p>
                                <p><i class="fas fa-paw"></i> @Html.ActionLink("Obtener Mascotas", "ObtenerAnimalesPorUsuario", "Animal", new { email = item.Email }, htmlAttributes: null)</p>
                                <p><i class="fas fa-trash"></i> @Html.ActionLink("Eliminar", "Delete", new { email = item.Email })</p>
                            </div>
                        </article>
                        }
                    }
                    else
                    {
                        <h2 style="margin-left: auto; margin-right: auto;">No hay ningún usuario que cumpla este filtro</h2>
                    }
                }
            </main>

            <br />
            @*Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount*@
            @if (Model.Any())
            {
                <p style="text-align: center;margin-top: 10px;font-size: 18px"> Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</p>
                @*<p style="text-align: center;">Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</p>*@
            }
            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            <p class="parrafoCentrar">
                <i class="fas fa-home"></i> @Html.ActionLink("Volver a inicio", "Indexad", "Home")
            </p>

WebProtectoraMilpatitas/Views/Usuario/Perfil.cshtml
@model WebProtectoraMilpatitas.Models.UsuarioViewModel
@using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
@{

    if (Session["Usuario"] != null)
    {
        if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_LayoutUsu.cshtml";
        }
    }
}


    <h2>Mis datos</h2>
    <section id="secanim">
        <main id="details">
            <article class="detalle">
                <h2>@Html.DisplayFor(model => model.Nombre)</h2>
                <div>
                    <p>
                        <b>@Html.DisplayNameFor(model => model.Nombre)</b>



                        @Html.DisplayFor(model => model.Nombre)
                    </p>
                    <p>

                        <b>@Html.DisplayNameFor(model => model.Email)</b>



                        @Html.DisplayFor(model => model.Email)
                    </p>

                 



                    <p>
                        <img style="width:200px;height:200px" src="/@Html.DisplayFor(model => model.Foto)" />
                    </p>
                </div>

                <div>
                    <p>
                        <i class="fas fa-pen"></i> @Html.ActionLink("Editar", "Edit", new { email = Model.Email })
                    </p>
                    @{

                        if (Session["Usuario"] != null)
                        {
                            if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(UsuarioEN))
                            {
                                <p>
                                    <i class="fas fa-paw"></i> @Html.ActionLink("Ver mis mascotas", "ObtenerAnimalesPorUsuario", "Animal", new { email = Model.Email }, htmlAttributes: null)
                                </p>
                                <p>
                                    <i class="fas fa-edit"></i> @Html.ActionLink("Ver mis solicitudes de adopción", "ObtenerSolicitudUsuario", "SolicitudAdopcion", new { email = Model.Email }, htmlAttributes: null)
                                </p>
                                <p>
                                    <i class="fas fa-file-signature"></i> @Html.ActionLink("Ver mis contratos de adopción", "ObtenerContratoUsuario", "ContratoAdopcion", new { email = Model.Email }, htmlAttributes: null)
                                </p>
                                <p>
                                    <i class="fas fa-eye"></i> @Html.ActionLink("Ver mis seguimientos", "ObtenerSeguimientoUsuario", "Seguimiento", new { email = Model.Email }, htmlAttributes: null)
                                </p>
                                <p>
                                    <i class="fas fa-comment-dots"></i> @Html.ActionLink("Chat con protectora", "Index", "Mensaje", new { email = Model.Email }, htmlAttributes: null)
                                </p>
                            }
                        }
                    }

                    <p>
                </div>
            </article>
        </main>
    </section>
<p class="parrafoCentrar">
    @{

        if (Session["Usuario"] != null)
        {
            if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
            {
                <i class="fas fa-home"></i> @Html.ActionLink("Volver a inicio", "Indexad", "Home")
            }
            else
            {
                <i class="fas fa-home"></i> @Html.ActionLink("Volver a inicio", "Index", "Home")
            }
        }
    }
  </p>