WebProtectoraMilpatitas/Controllers/EspecieController.cs
using ProtectoraMilpatitasGenNHibernate.CAD.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebProtectoraMilpatitas.Assemblers;
using WebProtectoraMilpatitas.Models;

namespace WebProtectoraMilpatitas.Controllers
{
    [Authorize]

    public class EspecieController : BasicController
    {
        // GET: Especie
        public ActionResult Index(int? page, string sortOrder, string nameSearch)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            EspecieCAD especieCAD = new EspecieCAD(session);
            EspecieCEN especieCEN = new EspecieCEN(especieCAD);
            IList<EspecieEN> listaEspecie = especieCEN.Dame_Todas(0, -1);

            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (!String.IsNullOrEmpty(nameSearch))
            {
                listaEspecie = listaEspecie.Where(s => s.Nombre.Contains(nameSearch)).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    listaEspecie = listaEspecie.OrderByDescending(s => s.Nombre).ToList();
                    break;
                default:
                    listaEspecie = listaEspecie.OrderBy(s => s.Nombre).ToList();
                    break;
            }

            IEnumerable<EspecieViewModel> listaView = new EspecieAssembler().ConvertListENToModel(listaEspecie).ToList();

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listaView.ToPagedList(pageNumber, pageSize));
        }

        // GET: Especie/Details/5
        public ActionResult Details(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();
            
            EspecieViewModel esp = null;
            EspecieEN espEN = new EspecieCAD(session).Dame_Por_Id(id);
            esp = new EspecieAssembler().ConvertENToModelUI(espEN);

            SessionClose();
            return View(esp);
        }

        // GET: Especie/Create
        public ActionResult Create()
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            return View();
        }

        // POST: Especie/Create
        [HttpPost]
        public ActionResult Create(EspecieViewModel esp)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add insert logic here

                EspecieCEN espCEN = new EspecieCEN();
                espCEN.Nuevo(esp.Nombre);

                TempData["mensajeModalEspecie"] = "Especie creada correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalEspecie"] = "Ha habido un error al crear la especie";
                return RedirectToAction("Index");
            }
        }

        // GET: Especie/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            EspecieViewModel esp = null;

            SessionInitialize();
            EspecieEN espEN = new EspecieCAD(session).Dame_Por_Id(id);
            esp = new EspecieAssembler().ConvertENToModelUI(espEN);
            SessionClose();

            return View(esp);
        }

        // POST: Especie/Edit/5
        [HttpPost]
        public ActionResult Edit(EspecieViewModel esp)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add update logic here

                EspecieCEN espcen = new EspecieCEN();
                espcen.Modificar(esp.Id, esp.Nombre);

                TempData["mensajeModalEspecie"] = "Especie editada correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalEspecie"] = "Ha habido un error al editar la especie";
                return RedirectToAction("Index");
            }
        }

        // GET: Especie/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();
            EspecieCAD espCad = new EspecieCAD(session);
            EspecieCEN especieCEN = new EspecieCEN(espCad);
            ViewData["NombreEsp"] = especieCEN.Dame_Por_Id(id).Nombre;

            SessionClose();
            return View();
        }

        // POST: Especie/Delete/5
        [HttpPost]
        public ActionResult Delete(EspecieViewModel esp)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add delete logic here
                EspecieCEN especieCEN = new EspecieCEN();
                especieCEN.Eliminar(esp.Id);

                TempData["mensajeModalEspecie"] = "Especie eliminada correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalEspecie"] = "Ha habido un error al eliminar la especie";
                return RedirectToAction("Index");
            }
        }
    }
}

WebProtectoraMilpatitas/Controllers/RazaController.cs
using ProtectoraMilpatitasGenNHibernate.CAD.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.CEN.ProtectoraMilpatitas;
using ProtectoraMilpatitasGenNHibernate.EN.ProtectoraMilpatitas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using WebProtectoraMilpatitas.Assemblers;
using WebProtectoraMilpatitas.Models;

namespace WebProtectoraMilpatitas.Controllers
{
    public class RazaController : BasicController
    {
        [Authorize]

        // GET: Raza
        public ActionResult Index(int? page, string sortOrder, string nameRazaSearch, string nameEspecieSearch)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            RazaCAD razCAD = new RazaCAD(session);
            RazaCEN razCEN = new RazaCEN(razCAD);

            IList<RazaEN> razsEN = razCEN.Dame_Todas(0, -1);

            ViewBag.NameRazaSort = String.IsNullOrEmpty(sortOrder) ? "nameRaza_desc" : "";
            ViewBag.NameEspecieSort = String.IsNullOrEmpty(sortOrder) ? "nameEspecie_desc" : "";

            if (!String.IsNullOrEmpty(nameRazaSearch))
            {
                razsEN = razsEN.Where(s => s.Nombre.Contains(nameRazaSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(nameEspecieSearch))
            {
                razsEN = razsEN.Where(s => s.Especie.Nombre.Contains(nameEspecieSearch)).ToList();
            }

            switch (sortOrder)
            {
                case "nameRaza_desc":
                    razsEN = razsEN.OrderByDescending(s => s.Nombre).ToList();
                    break;
                case "nameEspecie_desc":
                    razsEN = razsEN.OrderByDescending(s => s.Especie.Nombre).ToList();
                    break;
                default:
                    razsEN = razsEN.OrderBy(s => s.Nombre).ToList();
                    break;
            }

            IEnumerable<RazaViewModel> listaRazas = new RazaAssembler().ConvertListENToModel(razsEN).ToList();

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listaRazas.ToPagedList(pageNumber, pageSize));
        }

        // GET: Raza/Details/5
        public ActionResult Details(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            RazaViewModel raz = null;

            SessionInitialize();

            RazaEN razEN = new RazaCAD(session).Dame_Por_Id(id);

            raz = new RazaAssembler().ConvertENToModelUI(razEN);

            SessionClose();

            return View(raz);
        }

        // GET: Raza/Create
        public ActionResult Create()
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            IList<EspecieEN> listaEspecies = new EspecieCEN().Dame_Todas(0, -1);
            IList<SelectListItem> especiesItems = new List<SelectListItem>();

            foreach (EspecieEN esp in listaEspecies)
            {
                especiesItems.Add(new SelectListItem { Text = esp.Nombre, Value = esp.Id.ToString() });
            }

            ViewData["idEspecie"] = especiesItems;

            return View();
        }

        // POST: Raza/Create
        [HttpPost]
        public ActionResult Create(RazaViewModel raz)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add insert logic here

                RazaCEN razCEN = new RazaCEN();
                razCEN.Nuevo(raz.Nombre, raz.idEspecie);

                TempData["mensajeModalRaza"] = "Raza creada correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalRaza"] = "Ha habido un error al crear la raza";
                return RedirectToAction("Index");
            }
        }

        public ActionResult ObtenerRazasPorEspecie(int p_especie, int? page, string sortOrder, string nameRazaSearch, string nameEspecieSearch)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();

            RazaCAD razCad = new RazaCAD(session);
            EspecieCAD espeCad = new EspecieCAD(session);
            RazaCEN razCEN = new RazaCEN(razCad);
            IList<RazaEN> listRaz = razCEN.Dame_Raza_Por_Especie(p_especie);

            ViewBag.NameRazaSort = String.IsNullOrEmpty(sortOrder) ? "nameRaza_desc" : "";
            ViewBag.NameEspecieSort = String.IsNullOrEmpty(sortOrder) ? "nameEspecie_desc" : "";

            if (!String.IsNullOrEmpty(nameRazaSearch))
            {
                listRaz = listRaz.Where(s => s.Nombre.Contains(nameRazaSearch)).ToList();
            }

            if (!String.IsNullOrEmpty(nameEspecieSearch))
            {
                listRaz = listRaz.Where(s => s.Especie.Nombre.Contains(nameEspecieSearch)).ToList();
            }

            switch (sortOrder)
            {
                case "nameRaza_desc":
                    listRaz = listRaz.OrderByDescending(s => s.Nombre).ToList();
                    break;
                case "nameEspecie_desc":
                    listRaz = listRaz.OrderByDescending(s => s.Especie.Nombre).ToList();
                    break;
                default:
                    listRaz = listRaz.OrderBy(s => s.Nombre).ToList();
                    break;
            }

            IEnumerable<RazaViewModel> listRaz2 = new RazaAssembler().ConvertListENToModel(listRaz).ToList();
            EspecieEN espEN = espeCad.Dame_Por_Id(p_especie);

            ViewData["idEspecie"] = p_especie;

            if (espEN != null)
            {
                ViewData["NombreEspecie"] = espEN.Nombre;
            }

            SessionClose();

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            return View(listRaz2.ToPagedList(pageNumber, pageSize));
        }

        // GET: Raza/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            RazaViewModel raz = null;

            SessionInitialize();

            RazaEN razEN = new RazaCAD(session).Dame_Por_Id(id);

            raz = new RazaAssembler().ConvertENToModelUI(razEN);

            SessionClose();

            return View(raz);
        }

        // POST: Raza/Edit/5
        [HttpPost]
        public ActionResult Edit(RazaViewModel raz)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            try
            {
                // TODO: Add update logic here

                RazaCEN razCEN = new RazaCEN();
                razCEN.Modificar(raz.Id, raz.Nombre);

                TempData["mensajeModalRaza"] = "Raza editada correctamente";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensajeModalRaza"] = "Ha habido un error al editar la raza";
                return RedirectToAction("Index");
            }
        }

        // GET: Raza/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

            SessionInitialize();
            RazaCAD razCad = new RazaCAD(session);
            RazaCEN razaCEN = new RazaCEN(razCad);
            ViewData["NombreRaz"] = razaCEN.Dame_Por_Id(id).Nombre;

            SessionClose();
            return View();
        }

        // POST: Raza/Delete/5
        [HttpPost]
        public ActionResult Delete(RazaViewModel raz)
        {
            if (Session["Usuario"] != null)
            {
                if (((UsuarioEN)Session["Usuario"]).GetType() == typeof(AdministradorEN))
                {

                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

WebProtectoraMilpatitas/Views/Especie/Create.cshtml
@model WebProtectoraMilpatitas.Models.EspecieViewModel

@{
    ViewBag.Title = "Crear nueva especie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear nueva especie</h2>

@using (Html.BeginForm("Create", "Especie", FormMethod.Post, new { @class = "formGuapo" })) 
{
    @Html.AntiForgeryToken()
   

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<p class="text">
    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
</p>
    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear" class="btn btn-default" />
        </div>
    </div>
    }

    <div class="parrafoCentrar">
        @Html.ActionLink("Volver a la lista", "Index")
    </div>

WebProtectoraMilpatitas/Views/Especie/Delete.cshtml
@model WebProtectoraMilpatitas.Models.EspecieViewModel

@{
    ViewBag.Title = "Eliminar especie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar especie</h2>
<div class="formEliminarGuapo">
    <h2>¿Estás seguro de que quieres eliminar la especie @ViewData["NombreEsp"]?</h2>
</div>
<div>
    <hr />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color parrafoCentrar">
            <input type="submit" value="Eliminar" class="btn btn-default" /> | <i class="fas fa-paw"></i>
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

WebProtectoraMilpatitas/Views/Especie/Edit.cshtml
@model WebProtectoraMilpatitas.Models.EspecieViewModel

@{
    ViewBag.Title = "Editar especie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar especie</h2>

@using (Html.BeginForm("Edit", "Especie", FormMethod.Post, new { @class = "formGuapo" }))
{
    @Html.AntiForgeryToken()
    
    
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<p class="text">
    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })

    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
</p>
    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Editar" class="btn btn-default" />
        </div>
    </div>

    }

    <div class="parrafoCentrar">
        @Html.ActionLink("Volver a la lista", "Index")
    </div>

WebProtectoraMilpatitas/Views/Especie/Index.cshtml
@model PagedList.IPagedList<WebProtectoraMilpatitas.Models.EspecieViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index especies";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Especies</h2>

<h3>@Html.ActionLink("Razas", "Index", "Raza")</h3>

<p>
    <i class="fas fa-plus"></i> @Html.ActionLink("Crear nueva especie", "Create")
</p>

@if (((string)TempData["mensajeModalEspecie"]) != null)
{
    <div id="capafondo">

        <article id="ar">
            <h2>Especie</h2>
            <p>
                @((string)TempData["mensajeModalEspecie"])
            </p>
            <footer><button class="button" onclick="cerrarMensajeModal();">cerrar</button></footer>
        </article>
    </div>


}
<h2>Filtrar especies por: </h2>
<div class="readFilters" style="margin-right: auto;margin-left: auto;">
    <ul class="readFiltersUls">
        <li>
            @using (Html.BeginForm())
            {
            <p>

                <label class="textLabel">Buscar por nombre: </label>
                <label class="searchPoner">
                    @Html.TextBox("nameSearch")<input style="display:none;" id="buscEspecie" type="submit" value="Buscar" />
                    <label for="buscEspecie" style="margin-left: 10px;" class="fas fa-search"></label>
                </label>
            </p>

            }
        </li>
    </ul>
</div>
<h2>Ordenar especies por:</h2>
<div class="enlacesOrdenar">
            <h3 style="margin-left: auto;margin-right: auto;">@Html.ActionLink("Ordenar por nombre", "Index", new { sortOrder = ViewBag.NameSort })</h3>
</div>
<table class="table">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        <i class="fas fa-pen"></i> @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Obtener animales por especie", "ObtenerAnimalesPorEspecie", "Animal", new { p_especie = item.Id }, htmlAttributes: null) |
                        @Html.ActionLink("Obtener razas por especie", "ObtenerRazasPorEspecie", "Raza", new { p_especie = item.Id }, htmlAttributes: null) |
                        <i class="fas fa-trash"></i> @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

            </table>
            <br />
            @*Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount*@
            @if (Model.Any())
            {
                <p style="text-align: center;margin-top: 10px;font-size: 18px"> Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</p>
                @*<p style="text-align: center;">Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount</p>*@
            }
            @Html.PagedListPager(Model, page => Url.Action("Index",
                new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            <p>
                <i class="fas fa-paw"></i> @Html.ActionLink("Volver a animales", "Index", "Animal")
            </p>